### ISSUE TITLE
Little "Y" after category name: why?

### ISSUE THREAD

**Issue by IterationCorp** [andyhqtran/Divi-100-Article-Card#10]
### Problem:

Some of the category add an "Y" after the name of the category, why?

### Steps To Reproduce:
1. just look at : https://www.sagenda.com/blog/

**Comment by andyhqtran** [comment]
Hey @IterationCorp, it looks like you're on an older version of the plugin. You can [click here](https://github.com/andyhqtran/Divi-100-Article-Card/releases/tag/v0.0.2) to download v0.0.2

**Comment by IterationCorp** [comment]
Hello,
This solved the "Y" problem, but now I have a "Read more" overlappsed with the category tag!
![screen shot 2016-06-04 at 22 32 23](https://cloud.githubusercontent.com/assets/6637470/15801937/91392702-2aa4-11e6-9a7a-b73329e657d7.png)

**Comment by andyhqtran** [comment]
By default the blog grid module doesn't add read more. So this is due to a custom post plugin, or a setting that has been made.

**Comment by IterationCorp** [comment]
@andyhqtran -> this was not when I installed version 0.0.1 of your plugin and appeared when installing v0.0.2

**Comment by IterationCorp** [comment]
Hello @erikgeurts where didn't find it...

**Comment by andyhqtran** [comment]
As @erikgeurts stated, it should be an option available in the model.

**Comment by IterationCorp** [comment]
Not clear "_a setting while formatting the Blog module_" or "_an option available in the model._" should it be changed in the WP backend or is this a code change that I should handle with a child theme?
