### ISSUE TITLE
QUESTION: Can I insert this into my category pages?

### ISSUE THREAD

**Issue by mozakdesign** [andyhqtran/Divi-100-Article-Card#14]
Can I insert this into my category pages?

... any php I can insert into a child theme? 

Many thanks!

**Comment by andyhqtran** [comment]
Hey @mozakdesign when you're talking about category page, do you mean the Extra theme? At the moment, the plugin only supports Divi and Divi Child Theme and just needs to be installed via a plugin.

**Comment by mozakdesign** [comment]
I have a divi child theme

**Comment by andyhqtran** [comment]
Do you have a demo of what you mean? It might be easier for me to give you an explanation if I had a visual.

**Comment by mozakdesign** [comment]
want: https://mozakdesign.com/effective-website-design/   to look like: https://mozakdesign.com/web-design-blog/

so .. category.php, archive.php ...

**Comment by andyhqtran** [comment]
Ahh I see, at the time there's no option to change the category page since the plugin targets the Blog Grid Module.

**Comment by mozakdesign** [comment]
no php funtion call I can do in a child theme?

**Comment by andyhqtran** [comment]
The article card style is being applied through [JavaScript](https://github.com/andyhqtran/Divi-100-Article-Card/blob/master/assets/js/scripts.js). If you look at the code, you'll see that it's checking for any page that has the element [`.et_pb_blog_grid`](https://github.com/andyhqtran/Divi-100-Article-Card/blob/master/assets/js/scripts.js#L5).
