### ISSUE TITLE
Blog Entry Title Partially Covered

### ISSUE THREAD

**Issue by mikeve** [andyhqtran/Divi-100-Article-Card#15]
### Problem:

When hovering over a card, the extract expands and partially covers the title. It should either cover the title completely or not at all.

### Steps To Reproduce:
1. Go to http://test.iridian-optical-filters.com/news-and-events/news/
2. Hover over a card

### Additional Information:

**Device**: MacBook Pro

**Operating System**: El Capitan

**Browser**: Various

-

#### Before submitting your issue, please ensure the following:

* [ ] You have reproduced the issue using the latest code from the master branch of this repository.
* [ ] You searched Github for the issue and found no reports of the issue currently open.
* [ ] You properly formated the issue title – `Scope :: One sentence to describe the issue`.
* [ ] You have provided a detailed description of the issue.
* [ ] You have provided any/all relevant information: screenshot, screencast, ticket URL.
* [ ] You have provided the steps that one must take to reproduce the issue.

**Comment by andyhqtran** [comment]
@mikeve did you make in custom changes to the module itself? The code is made to read the DOM of the original Blog Grid Module.

**Comment by mikeve** [comment]
Yes. I made a change (in the child theme) suggested by Eduard to allow for asc/des order selection.

All works well with Divi activated. Sorry for the kerfuffle.
