### ISSUE TITLE
Doesn't show extract when using Divi Builder to create posts

### ISSUE THREAD

**Issue by j-dray** [andyhqtran/Divi-100-Article-Card#17]
### Problem:

The extract slides up fine on posts I made using the standard post builder. But I'm transitioning to a layout built with Divi Builder, and now I've done that and moved my content into a Text module, the extract no longer slides up. Is there a way to tell it to pull this content from somewhere else?

### Steps To Reproduce:
1.
2.
3.
4.

### Additional Information:

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Reference**:

-

#### Before submitting your issue, please ensure the following:

* [ ] You have reproduced the issue using the latest code from the master branch of this repository.
* [ ] You searched Github for the issue and found no reports of the issue currently open.
* [ ] You properly formated the issue title – `Scope :: One sentence to describe the issue`.
* [ ] You have provided a detailed description of the issue.
* [ ] You have provided any/all relevant information: screenshot, screencast, ticket URL.
* [ ] You have provided the steps that one must take to reproduce the issue.

**Comment by andyhqtran** [comment]
Please follow our guidelines by filling out the information so I can further assist you.
