### ISSUE TITLE
second category obscured/font size

### ISSUE THREAD

**Issue by philsimon** [andyhqtran/divi-100-article-card#2]
Thanks. It looks awesome but can you tell me how to manage how categories are displayed?

http://screencast.com/t/NhCwYBBe

The second category on the first post is obscured. Thanks!

It would also be useful to be able to increase the excerpt's font size.

**Comment by andyhqtran** [comment]
@philsimon to increase the font size, you can add something like this to your header via the Divi Control Panel...

```
.divi-100-article-card .et_pb_blog_grid .article-card .article-card__excerpt {
  font-size: 14px;
}
```

**Comment by philsimon** [comment]
Thanks.

**Comment by andyhqtran** [comment]
Plugin has been updated and you can get the latest version here.
https://github.com/andyhqtran/divi-100-article-card/releases/tag/v0.0.2

**Comment by philsimon** [comment]
Sweet. I've put this on both of my sites. You rock.

**Comment by andyhqtran** [comment]
Awesome, glad it's working!
