### ISSUE TITLE
Possible for excerpt to be formatted

### ISSUE THREAD

**Issue by swilky** [andyhqtran/Divi-100-Article-Card#20]
#### Before submitting your issue, please ensure the following:
* [ ] You have reproduced the issue in the latest version of this plugin.
* [ ] You searched Github for the issue and found no reports of the issue currently open.
* [ ] You properly formated the issue title – `Scope :: One sentence to describe the issue`.
* [ ] You have provided a detailed description of the issue.
* [ ] You have provided any/all relevant information: screenshot, screencast.
* [ ] You have provided the steps that one must take to reproduce the issue.

_Warning: Please make sure that your issue is detailed, otherwise the ticket will not be prioritized due to lack of information._

-

### Problem:
Hi There
I have included excerpts on my posts as I would like them to show when the visitor hovers over the article in the grid. My excerpts are formatted using the rich text excerpts plugin. An example of an excerpt is -
Serves: 4
Cooking Time: 20 Minutes
Calories: 400

Is it possible for the excerpts to be formatted in the divi article card? Currently an excerpt such as the one above would be displayed as
Serves: 4 Cooking
Time: 20 Minutes
Calories: 100

### Steps To Reproduce:

1.
2.
3.
4.

### Additional Information:

**Divi Version**: 2.7.5

**Child Theme**: Yes

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Reference**:

**Comment by andyhqtran** [comment]
Excerpts are copied from the original text, optimized and trimed to remove all white spaces add to it. Try using `<br>`

**Comment by swilky** [comment]
Hi Andy, I tried that but unfortunately it doesn't work... any ideas?

**Comment by andyhqtran** [comment]
@swilky I can you take a look at v0.0.3? That copies the full HTML instead of text in Divi v2.7.7 and above.

**Comment by swilky** [comment]
Hi Andy
That's great thank you it works fine now!
