### ISSUE TITLE
Plugin Fails to install produces browser error ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by mooteki** [andyhqtran/Divi-100-Article-Card#21]
### Problem:
After trying to install the plugin.
Browser returns with the following error message below:

![screenshot](https://cloud.githubusercontent.com/assets/1243644/15903469/7fc21bbc-2ddf-11e6-92d0-a53c117fcda5.png)

I tried to install other plugins like the "divi-100-hamburger-menu.zip" plugin with no problems.

### Steps To Reproduce:

1. Downloaded plugin from: http://www.elegantthemes.com/blog/divi-resources/free-divi-extension-gives-the-divi-blog-module-a-brand-new-look. Also tried downloading it from this source: https://github.com/andyhqtran/Divi-100-Article-Card/releases
2. From the wordpress admin panel: Plugin>>Add new>>Upload Plugin>>Choose File>>
3. Select "divi-100-article-card.zip" from drive
4. Click "Install now" button
5. Browser Returns with error message indicated above

### Additional Information:

**Wordpress Version**:  WordPress v4.5.2

**Divi Version**: Divi v 2.7.5

**Child Theme**: None - Uses Default Parent Theme

**Device**:  MacBook Pro (mid 2012)

**Operating System**:  OSX Yosemite v10.10.5

**Browser**: Chrome  v51.0.2704.84 (64-bit)

**Screen Resolution**: 1280 x 800

**Hosting Service**: GoDaddy Deluxe Linux Hosting with cPanel

Would appreciate any help.

Cheers!

**Comment by andyhqtran** [comment]
Since this is a GoDaddy issue, I'll be closing this issue since it's a duplicate. Ref issue #18 to keep up to date with the progress on it.
