### ISSUE TITLE
Article Card loses all post grid formatting rendering it unreadable

### ISSUE THREAD

**Issue by UROCKlive1** [andyhqtran/Divi-100-Article-Card#22]
I installed this plugin and it wiped out enough of the blog grid formatting to render it unreadable. My black backgrounds became white and my white font stayed white. So I had a bunch of big white squares with no readable text. I have a screenshot, but I can't leave it that way for you to look at.

Too bad, I really hoped it would fix the uneven blog grid I've been trying to fix for months. Instead, the grid was still uneven, and then it totally messed up the rest of the page. A three column feed display that previously looked great suddenly put everything in one long column to the left with a bunch of blank page everywhere else. Worse still, deactivating the plugin did not fix it. I had to delete the entire module, get fresh code and start it over.

I have the latest version of WP, Divi and as far as I know of this plugin. I'm on Windows 7 and 10 and OS whatever is right before El Capitan.

I don't know how you can replicate the problem because I can't leave it looking like that. Attaching screenshots.
![ac prob 1 music news urock musically gifted](https://cloud.githubusercontent.com/assets/19830942/15919419/09a63dfa-2dc6-11e6-979c-935074500061.png)
![ac prob 2 music news urock musically gifted](https://cloud.githubusercontent.com/assets/19830942/15919428/14b38c52-2dc6-11e6-8d1a-8b1cc922471f.png)

**Comment by andyhqtran** [comment]
This plugin is made to remodel the standard Divi Blog Grid module and wasn't created to support 3rd party plugins. With just a screen shot alone I won't be able to help resolve this issue since I won't have a place I can reference too.
