### ISSUE TITLE
Activation should be possible on module or at least page level

### ISSUE THREAD

**Issue by mike-leber** [andyhqtran/Divi-100-Article-Card#24]
Currently the module is activated for all blog modules across a site. It would be great to enable it selectively on a more granular level (per blog module or at least per page)

**Comment by andyhqtran** [comment]
At the moment there’s no option to specify a page. However if you want to disable it on a page, what you can do is create a Code Module and add the following code to it.
```js
<script>jQuery(document).ready(function ($) {$(‘body’).removeClass(‘divi-100-article-card’);})<script>
```
