### ISSUE TITLE
Latest Divi release breaks article card

### ISSUE THREAD

**Issue by philsimon** [andyhqtran/Divi-100-Article-Card#26]
See here:

[http://screencast.com/t/x9sejMAphYZ]

Anyone else have this problem? Thanks.

**Comment by erikgeurts** [comment]
Duplicate, see #25

**Comment by erikgeurts** [comment]
@philsimon You might want to close this issue you created to avoid cluttering the list.

**Comment by philsimon** [comment]
Closed. It's a duplicate issue. @erikgeurts - thanks.
