### ISSUE TITLE
Can't Install Article Card

### ISSUE THREAD

**Issue by EagleSan** [andyhqtran/Divi-100-Article-Card#27]
Problem:
When trying to add the plugin WP won't accept it. All the other layout packs, and plugin (hamburger, login) work, but not this one.

### Steps To Reproduce:

1. Download latest version of the plugin ~ divi-100-article-card.zip
2. Add plugin
3. Browse for plugin
4. Click Install Now
5. Receive the message ~ The connection was reset

### Additional Information:

**WP Version**: WordPress 4.5.3 running Divi theme.

**Divi Version**: DiviVersion: 2.7.3

**Child Theme**: none used

**Device**: iMac (21.5-inch, Mid 2010)

**Operating System**: Mac OS 10.11.5 El Capitan

**Browser**: Firefox 47.0

**Screen Resolution**: 21.5-inch (1920 x 1080)

**Hosting Service**: GoDaddy

![divi 1](https://cloud.githubusercontent.com/assets/20097295/16281357/4f85026e-3881-11e6-818d-28c45b39657b.jpg)
![divi 2](https://cloud.githubusercontent.com/assets/20097295/16281358/4f917120-3881-11e6-9eef-4ecb921dcb4a.jpg)

**Comment by EagleSan** [comment]
What the hell. This is suppose to be a support site when we have problems yet not a single response to help me?

**Comment by andyhqtran** [comment]
Since this is a GoDaddy issue, I'll be closing this issue since it's a duplicate. Ref issue #18 to keep up to date with the progress on it.
