### ISSUE TITLE
End of Divi -100-Article-CArd

### ISSUE THREAD

**Issue by dentaoman** [andyhqtran/Divi-100-Article-Card#28]
#### Before submitting your issue, please ensure the following:
* [ ] You have reproduced the issue in the latest version of this plugin.
* [ ] You searched Github for the issue and found no reports of the issue currently open.
* [ ] You properly formated the issue title – `Scope :: One sentence to describe the issue`.
* [ ] You have provided a detailed description of the issue.
* [ ] You have provided any/all relevant information: screenshot, screencast.
* [ ] You have provided the steps that one must take to reproduce the issue.

_Warning: Please make sure that your issue is detailed, otherwise the ticket will not be prioritized due to lack of information._

-

### Problem:
Since upgrade to 2.7.7
Only Enable or Disable
![screenshot_1681](https://cloud.githubusercontent.com/assets/15379390/16320935/ac30459a-399a-11e6-949c-53d5ef978f16.jpg)

### Steps To Reproduce:

1.
2.
3.
4.

### Additional Information:

**Divi Version**:

**Child Theme**:

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Reference**:

**Comment by andyhqtran** [comment]
@dentaoman I am unable to understand what the issue is here. Please make sure you read the guidelines and fill in all the information.

**Comment by dentaoman** [comment]
Sorry a mistake, I forgot you had to go to grid blog parameters...
