### ISSUE TITLE
More than 1 category

### ISSUE THREAD

**Issue by laylaroberts** [andyhqtran/divi-100-article-card#3]
### Problem:

If there is more than 1 category, they overlap, so neither can be read. The overall effect is awesome if there is just 1 category, but this looks messy.

### Steps To Reproduce:
1. See: http://www.sydneyconcierge.com.au/sydney-blog
2. See: http://www.conciergeconnections.com.au/concierge-blog.html
3.
4.

### Additional Information:

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Reference**:

-

#### Before submitting your issue, please ensure the following:

* [ ] You have reproduced the issue using the latest code from the master branch of this repository.
* [ ] You searched Github for the issue and found no reports of the issue currently open.
* [ ] You properly formated the issue title – `Scope :: One sentence to describe the issue`.
* [ ] You have provided a detailed description of the issue.
* [ ] You have provided any/all relevant information: screenshot, screencast, ticket URL.
* [ ] You have provided the steps that one must take to reproduce the issue.

**Comment by andyhqtran** [comment]
Ref #2
