### ISSUE TITLE
thumbnails not displayed on card

### ISSUE THREAD

**Issue by insighthought** [andyhqtran/Divi-100-Article-Card#35]
#### Before submitting your issue, please ensure the following:
* [ ] You have reproduced the issue in the latest version of this plugin.
* [ ] You searched Github for the issue and found no reports of the issue currently open.
* [ ] You properly formated the issue title – `Scope :: One sentence to describe the issue`.
* [ ] You have provided a detailed description of the issue.
* [ ] You have provided any/all relevant information: screenshot, screencast.
* [ ] You have provided the steps that one must take to reproduce the issue.

_Warning: Please make sure that your issue is detailed, otherwise the ticket will not be prioritized due to lack of information._
http://insighthought.com/short-and-not-so-sweet-blog/
blog in grid and show featured image enabled
-

### Problem:
Replace this with a description of the issue you are reporting. Be sure to explain expected results vs. actual results when it might not be obvious to those who will read your report.

### Steps To Reproduce:

1.
2.
3.
4.

### Additional Information:

**Divi Version**:

**Child Theme**:

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Reference**:

**Comment by andyhqtran** [comment]
Please make sure you follow the proper [format](https://github.com/andyhqtran/Divi-100-Article-Card#bugs--questions) when creating an issue. Due to lack of information, this issue will be closed. Please feel free to recreate an issue following the guidelines.
