### ISSUE TITLE
Content and title move up too high on hover

### ISSUE THREAD

**Issue by Ver3** [andyhqtran/Divi-100-Article-Card#37]
### Problem:
When you hover over an article card, the content and title move up too high. In some cases you're not even able to click the article title and thus are unable to read it.

### Steps To Reproduce:

1. Go to https://qmm.nl/blog/
2. Hover over any article.

### Additional Information:

**Divi Version**: Latest

**Child Theme**: Yes

**Device**: Mac and Win

**Operating System**: OSX, MacOS, Windows 10

**Browser**: Safari, Chrome

**Screen Resolution**: 1280x800

**Comment**: The same result comes up on other sites where Article Card v0.0.3 is used. It did not happen with the first version (which cannot be used anymore due to it's own issues.

Hope this helps you helping all users of this plugin.

**Comment by erikgeurts** [comment]
Add an excerpt to your post, or make the excerpt shorter. Be sure to enable display of excerpts in your blog grid.

**Comment by Ver3** [comment]
Bedankt Erik! (or "Thank you Erik" in case you're not Dutch)

This works. I feel silly for thinking it was bug. Glad to find out it was the user.. again :-)

One final question, is it possible to make the grid items always the same size (in order to create a symmetrical grid)?

**Comment by erikgeurts** [comment]
In my sites they are equally high, probably because I take care of making the excerpts all about the same length.

**Comment by Ver3** [comment]
I'll try that. Thank you again.

**Comment by andyhqtran** [comment]
Issue resolved thanks to @erikgeurts 🎉
