### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tallmeerkat** [andyhqtran/Divi-100-Article-Card#38]
### Problem:
I have installed the latest version of the plugin, set the blog page layout to grid and chosen the accent colour. However the plugin isn't working at all on this site. I have tried deactivating all the other plugins to see if there was a conflict but there doesn't appear to be.

### Steps To Reproduce:

1.installed the latest version
2.set the blog page layout to grid
3. chosen the accent colour
4. Deleted the plugin and tried 1-3 again
 URL [ http://toscalahiri.com/](url)

### Additional Information:

**Divi Version**:2.7.8

**Child Theme**:yes

**Device**:  PC

**Operating System**: Windows 10

**Browser**: Chrome

**Screen Resolution**:

**Reference**:

**Comment by andyhqtran** [comment]
![image](https://cloud.githubusercontent.com/assets/6789067/17147541/16e00dda-5318-11e6-8682-d1b23163a334.png)
Are you still having trouble with this? It seems to have been fixed.

**Comment by norbertledu** [comment]
@tallmeerkat how did you fix that? I have similar issue :-(
