### ISSUE TITLE
Divi Article Cards Plugin Breaks Pantheon Git Workflow

### ISSUE THREAD

**Issue by heretiq** [andyhqtran/Divi-100-Article-Card#39]
### Problem:
Great plugin; however we're having an issue that may be related to the plugin architecture and Git. We're building a client site on Pantheon and loading the Article Card plugin causes the Pantheon Git commit/restore/sync workflow to fail. 

Here's the root cause according to Pantheon:

"It looks like you have a Git submodule in your code repo which is causing workflow errors. Restoring or syncing code is failing because of the following error:

exit status 128: fatal: Not a git repository: wp-content/plugins/divi-article-cards/divi-100-setup/../.git/modules/divi-100-setup
Git submodules are currently not supported on the platform, please see- https://pantheon.io/docs/git-faq/#does-pantheon-support-git-submodules?.

Once you've removed the .git folder, you should be all set!" 

There is no .git folder in the plugin archive -- so I suspect that either the plugin creates a .git folder upon install or something else is awry. 

### Steps To Reproduce:

1. Install Article Cards plugin (via WP Admin or FTP) on a Divi website hosted on Pantheon 
2. Go to pantheon Dashboard
3. Notice the code update is not detected and does not trigger a commit 

### Additional Information:

**Divi Version**: 2.7.8

**Child Theme**: Custom, Derived from Divi

**Device**: N/A

**Operating System**: N/A

**Browser**: N/A

**Screen Resolution**: N/A

**Reference**:

**Comment by andyhqtran** [comment]
Hey there,

In this project, the submodules purpose is the allow us to update and maintain the core files of each plugin released with the Divi 100 series with ease.

-

After going over Pantheon, it looks like this issue doesn't have anything to do with the plugin architecture or Git because [Git submodules](https://git-scm.com/docs/git-submodule) isn't a GitHub or plugin exclusive feature. It's a feature provided by [Git](https://git-scm.com).

Due to Pantheon's lack of support for Git submodule, I recommend that you download the plugin from our [Git releases](https://github.com/andyhqtran/Divi-100-Article-Card/releases/) page, which would include the submodule, instead of cloning it via Git.

**Comment by heretiq** [comment]
Hi Andy,

Thanks for the prompt follow-up. I think there might be a misunderstanding. 

I'm not cloning the plugin via Git. I have uploaded the plugin file to the site in one of two ways:

1. Via the WP Admin Plugin Upload feature
2. Directly via SFTP

Pantheon syncs all code - whether uploaded via admin, sftp or Git - to a Git repo for source code management. 

In either case the site file tree ends up with a .git entry. Please see attached screenshot showing the .git file which contains: "gitdir: ../.git/modules/divi-100-setup" .. which Pantheon finds problematic as stated in the initial issue comment:

"It looks like you have a Git submodule in your code repo which is causing workflow errors. Restoring or syncing code is failing because of the following error:

exit status 128: fatal: Not a git repository: wp-content/plugins/divi-article-cards/divi-100-setup/../.git/modules/divi-100-setup
Git submodules are currently not supported on the platform, please see- https://pantheon.io/docs/git-faq/#does-pantheon-support-git-submodules?.

Once you've removed the .git folder, you should be all set!"

I followed your suggestion and downloaded the latest plugin from the Git releases page you linked to, then uploaded it via the WP admin dashboard. The problem persists. 

Thoughts?

**Comment by heretiq** [comment]
Hi Andy,

The problem was corrected by removing the .git file from the 'divi-100-setup' folder. 

If other Divi 100 plugins use this approach, these resources will cause problems with all Divi sites hosted on Pantheon. This is because Pantheon does not support Git sub modules within a site repository.

Can you advise if other Divi 100 plugins or resources use this approach?

**Comment by andyhqtran** [comment]
@heretiq my apologies didn't realize that it downloaded instead of cloned. I've made the adjustments and removed the .git folder from the submodule.

**Comment by heretiq** [comment]
@andyhqtran excellent. Two questions: 

1. Does that mean that the official plugin no longer includes the .git file?
2. If the answer is yes, will the plugin be updated on the Git releases page? 

Thanks.
