### ISSUE TITLE
Making article card excerpt into a link

### ISSUE THREAD

**Issue by mellotonik** [andyhqtran/Divi-100-Article-Card#41]
#### Before submitting your issue, please ensure the following:
* [x] You have reproduced the issue in the latest version of this plugin.
* [x] You searched Github for the issue and found no reports of the issue currently open.
* [x] You properly formated the issue title – `Scope :: One sentence to describe the issue`.
* [x] You have provided a detailed description of the issue.
* [x] You have provided any/all relevant information: screenshot, screencast.
* [x] You have provided the steps that one must take to reproduce the issue.

_Warning: Please make sure that your issue is detailed, otherwise the ticket will not be prioritized due to lack of information._

-

### Problem:
I'd like to have it so that the excerpt of the text itself is clickable and takes the user to the blog post. I've tried editing a few files but can't seem to get anywhere. 

### Steps To Reproduce:

1. Blog in grid mode
2. Hover over an article card
3.
4.

### Additional Information:

**Divi Version**: Latest

**Child Theme**: Yes

**Device**: 

**Operating System**: 

**Browser**:

**Screen Resolution**:

**Reference**:

**Comment by mtsweir** [comment]
I have a similar issue: http://www.smartsafetysolutions.co.nz/blog/

Is it possible to make the whole card clickable? I've had feedback from users saying they can't click to the article. It's a little unintuitive also, when I hover over the tile the title moves away from the mouse and I have to move up to click it. If this can be done let me know!

**Comment by Leannn** [comment]
Agreed that this is unintuitive, especially on smaller screens like tablets. 

If this can be fixed please let me know as well.

**Comment by erikgeurts** [comment]
This has already been implemented.

**Comment by andyhqtran** [comment]
@erikgeurts stated, the latest version implements this.

## 

Check out the release page for more information. https://github.com/andyhqtran/Divi-100-Article-Card/releases
