### ISSUE TITLE
Per Category Accent Color

### ISSUE THREAD

**Issue by heretiq** [andyhqtran/Divi-100-Article-Card#43]
### Problem:
The Divi Article Cards plugin allows a single Accent color to be set. It would be very useful to allow different accent colors to be set for each blog category -- or allow N accent colors to be set/mapped to select blog categories and a default accent color that is applied to categories not mapped to the N accent colors.

Is this possible?

### Steps To Reproduce:
N/A -- This is a feature request not a bug report.

### Additional Information:
**Divi Version**: 2.7.9
**Child Theme**: Yes, custom Divi child theme is present.

**Comment by andyhqtran** [comment]
Currently Divi doesn't have an option to set a specific color for each category so there's no way of targeting a specific color for each category for the article card. I recommend that you suggest this feature on the Divi support forum. :)
