### ISSUE TITLE
Cannot click on Article in blog with Article Card enabled

### ISSUE THREAD

**Issue by skftex** [andyhqtran/Divi-100-Article-Card#46]
#### Before submitting your issue, please ensure the following:
* [x] You have reproduced the issue in the latest version of this plugin.
* [x] You searched Github for the issue and found no reports of the issue currently open.
* [x] You properly formated the issue title – `Scope :: One sentence to describe the issue`.
* [x] You have provided a detailed description of the issue.
* [x] You have provided any/all relevant information: screenshot, screencast.
* [x] You have provided the steps that one must take to reproduce the issue.

_Warning: Please make sure that your issue is detailed, otherwise the ticket will not be prioritized due to lack of information._

-

### Problem:
The article cards on my blog page are no longer working. When you mouse over one of the entries, the text that is showing from the content preview moves up and you cannot click on the article to open it.  I disabled the plug-in and deleted it, downloaded the latest version, and it still has the same problem.  I'm not sure when the problem started but I hadn't made changes to the site in a while, other than normal updates of Divi and plug-ins.  I have attached screen shots. 

### Steps To Reproduce:

1. Install and activate extension
2. Enable extension in Divi 100
3. Go to blog page and mouse over blog entry
4.

### Additional Information:

**Divi Version**: 2.7.10

**Child Theme**: Yes.

**Device**: 

**Operating System**: 

**Browser**: Firefox, Chrome

**Screen Resolution**:

**Reference**:
![screenshot article card after mouse over](https://cloud.githubusercontent.com/assets/21128878/17817390/87f5d84c-65fb-11e6-9ed2-cde11369f519.jpg)
![screenshot-article card before mouse over](https://cloud.githubusercontent.com/assets/21128878/17817391/87fe1f0c-65fb-11e6-8a39-9f43bce7e514.jpg)

**Comment by nourishsoap** [comment]
The same thing happens on my page.  The article cards in their 'active' state open up in such a way that you cannot click on the title of the article to open it.  Almost like they are opening too far.  Please help!

**Comment by SiestaLOL** [comment]
I think if you make your except text shorter then that fixes it. It did on my version.

**Comment by skftex** [comment]
Since it wasn't doing that when I installed it, I shouldn't have to change the excerpt text size. Something changed that made this extension no longer work. I'd rather the extension be fixed rather than me trying to trick it into working. I'll just not use it otherwise.

**Comment by nourishsoap** [comment]
Thanks SiestaLOL - where do you shorten that excerpt please?  I've 
scouted around for just such a place but not found it.  Thanks and have 
a beautiful day further..


Kind Regards,

Pauline Susman

Soap Alchemist Extraordinaire


Soaps for daily use, Promotional Soap,
Pet Shampoo Bars, Guesthouse Soaps,
Hair Shampoo Bars, Custom Soaps

www.nourishsoaps.com

**Comment by SiestaLOL** [comment]
The excerpt is at the bottom of each post. You might have to turn it on in the top section to see it (go to 'screen options' at the top and turn on the excerpt. However, if you're not using an excerpt, then it might just be showing a bunch of stuff from the post? I found that if there were too many lines then it filled it up completely and pushed the image and link up too far. By using an excerpt you can just put in a couple little lines and control how big it is. But you may not want to use it that way.

**Comment by nourishsoap** [comment]
Exactly the issue I've had - it pushes up the image and link too far.  
I've found where to change the excerpt. Thanks so much!!


Kind Regards,

Pauline Susman

Soap Alchemist Extraordinaire


Soaps for daily use, Promotional Soap,
Pet Shampoo Bars, Guesthouse Soaps,
Hair Shampoo Bars, Custom Soaps

www.nourishsoaps.com

**Comment by skftex** [comment]
I appreciate that you were trying to help but I just don't feel that is an adequate fix. I have pages of blog posts and going through them one by one to fix the excerpt length just isn't an acceptable fix. If this had been an issue when the extension was installed, okay, but it wasn't doing this at first so something changed to break it. Going through every post to fix something isn't a solution, it is a work around.

**Comment by skftex** [comment]
Just to update, based on the excerpts suggestion. First off, I do not have manual excerpts set up for my posts so it cannot be that they are too long. I do have excerpts selected in the screen settings. I chose one post and turned this off, and still have the problem.

**Comment by andyhqtran** [comment]
This has been fixed in the latest version. v0.0.4.
