### ISSUE TITLE
 I can not upload the Divi-100-Article-Cards via the plugin upload.

### ISSUE THREAD

**Issue by bethedrm** [andyhqtran/Divi-100-Article-Card#5]
### Problem: I can not upload the Divi-100-Article-Cards via the plugin upload.

I have the latest Divi Theme.  I have downloaded the Divi-100-Article-Cards.zip file.  I follow the directions and it starts uploading via the plugin upload and then quits and gives me an error message that the site can't be reached.  The zip file is on my desktop.  I have closed the firewall for 10 minutes hoping that would allow it to access what it needs.  Where is it going to pull info and I will set it up as a trusted site if that is the case.  I have tried it on 3 different sites that I manage.  No luck.
I am really excited to use this plug in.  Thank you for your help.

### Steps To Reproduce:
1.
2.
3.
4.

### Additional Information:

**Device**:

**Operating System**:  Microsoft Windows 10  and Microsoft Windows 7

**Browser**:  Chrome, Firefox

**Screen Resolution**:  

**Reference**:

-

#### Before submitting your issue, please ensure the following:

* [ ] You have reproduced the issue using the latest code from the master branch of this repository.
* [ ] You searched Github for the issue and found no reports of the issue currently open.
* [ ] You properly formated the issue title – `Scope :: One sentence to describe the issue`.
* [ ] You have provided a detailed description of the issue.
* [ ] You have provided any/all relevant information: screenshot, screencast, ticket URL.
* [ ] You have provided the steps that one must take to reproduce the issue.

**Comment by mckernanin** [comment]
@bethedrm unfortunately this is a problem with your site, not with this plugin. You could try uploading it manually via FTP to /wp-content/plugins/ and then activating it from the dashboard.

**Comment by bethedrm** [comment]
Hi Kevin,
 
Thank you so much for your quick reply!!!  Much appreciated.  Using the FTP it worked great.  
 
Thanks again!!!

**Comment by andyhqtran** [comment]
Thanks @mckernanin for tackling this issue!
