### ISSUE TITLE
HTTP error with media

### ISSUE THREAD

**Issue by NBcraftscouncil** [andyhqtran/Divi-100-Article-Card#53]
Hi!

I've installed the divi blog plugin but now I'm not able to upload media, it's saying that there's an HTTP error. When I disable to plugin everything go back to normal!

Thanks

**Comment by andyhqtran** [comment]
Hey @NBcraftscouncil, please create a new ticket following the [issue guidelines](https://github.com/andyhqtran/divi-100-article-card/blob/master/.github/ISSUE_TEMPLATE.md) for me to better assist you.
