### ISSUE TITLE
Unable to click through to blog post on new design. Love the look, just not working right.

### ISSUE THREAD

**Issue by Samadi999** [andyhqtran/Divi-100-Article-Card#54]
## 
### Problem:

Cannot click to blog post on new look. Category not showing either so I disabled on my blog at www.achieveit360.com/blog
### Steps To Reproduce:

1.
2.
3.
4.
### Additional Information:

**Divi Version**: 3.0

**Child Theme**:

**Device**: MAC/PC

**Operating System**:

**Browser**: Firefox

**Screen Resolution**:

**Reference**:

**Comment by andyhqtran** [comment]
What version of the plugin are you using?

**Comment by Samadi999** [comment]
It’s the 0.3 version of the Plugin….

**Comment by andyhqtran** [comment]
There is a version 0.0.4 of the plugin that's available on the release page.
https://github.com/andyhqtran/Divi-100-Article-Card/releases

**Comment by Samadi999** [comment]
Thank you I will try that :)

**Comment by Samadi999** [comment]
Thank you! This works now, but I still don’t see the category showing….is this possible? Thanks for your help,

Andrea

**Comment by andyhqtran** [comment]
Categories should be showing if you haven't made any additional modifications to it.

**Comment by Samadi999** [comment]
This is what it looks like now http://achieveit360.com/blog/ 

Is this correct? How do I get the category to show?

Thank you,

Andrea

**Comment by andyhqtran** [comment]
Are the module settings default?

**Comment by Samadi999** [comment]
Thank you, it’s fixed now, appreciate your help!

Andrea

**Comment by andyhqtran** [comment]
Awesome, glad to help! 👍
