### ISSUE TITLE
DiviArticle Card plugin not working with Divi 3.071

### ISSUE THREAD

**Issue by milenasg123** [andyhqtran/Divi-100-Article-Card#72]
#### Before submitting your issue, please ensure the following:
* [ ] You have reproduced the issue in the latest version of this plugin.
* [ ] You searched Github for the issue and found no reports of the issue currently open.
* [ ] You properly formated the issue title – `Scope :: One sentence to describe the issue`.
* [ ] You have provided a detailed description of the issue.
* [ ] You have provided any/all relevant information: screenshot, screencast.
* [ ] You have provided the steps that one must take to reproduce the issue.

### Problem:

The blog articles displaying Fullwidth instead of Grid style after the latest Divi update.
The issue is related to Desktop view. Mobile view has always had 1 style displayed, and it's showing ok.

Please see my website, www.englishmadesimple.net via desktop.

How do I fix this?

Thanks

### Steps To Reproduce:

1.
2.
3.
4.

### Additional Information:

**Divi Version**:

**Child Theme**:

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Reference**:

**Comment by erikgeurts** [comment]
Works fine for me. I have Divi Article Cards Version 0.0.4 and Divi 3.0.71.
